import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./component/theme-provider";
import { DatabaseProvider } from "./contexts/DatabaseContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DatabaseProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            themes={['pink','yellow', 'light', 'dark']}
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </DatabaseProvider>
      </body>
    </html>
  );
}
